### POST id request to SSE endpoint
POST http://{{baseUrl}}/api/v1/sse/query
Content-Type: application/json

{
  "subscription": {
    "channel": "{{channel}}",
    "username": "{{username}}"
  },
  "query" : {
    "offset" : 1,
    "limit" : 10
  }
}