### POST request to SSE endpoint
POST http://localhost:8080/api/v1/sse/mangila-livestream/list?streamKey=helloworld
Content-Type: application/json

{
  "offset": 0,
  "limit": 10
}

### GET request to SSE endpoint
GET http://localhost:8080/api/v1/sse/mangila-livestream/id?streamKey=helloworld&id=1